export const captcha = '/captcha'
export const auth = '/auth'
export const profile = '/profile'
export const articles = '/articles'
export const stats = '/stats'
export const hubs = '/hubs'
export const funds = '/funds'
