export const SET_TOKEN = 'SET_TOKEN'
export const SET_REGISTER_CAPTCHA = 'SET_REGISTER_CAPTCHA'
export const SET_REGISTER_DATA = 'SET_REGISTER_DATA'
export const SET_PROFILE = 'SET_PROFILE'

export const SET_ARTICLES = 'SET_ARTICLES'
export const SET_ARTICLES_CONTEXT = 'SET_ARTICLES_CONTEXT'

export const SET_GENERAL_STATS = 'SET_GENERAL_STATS'

export const SET_HUBS = 'SET_HUBS'
export const SET_HUBS_CONTEXT = 'SET_HUBS_CONTEXT'

export const SET_TAGS = 'SET_TAGS'
export const SET_TAGS_CONTEXT = 'SET_TAGS_CONTEXT'

export const SET_ORGANIZATIONS = 'SET_ORGANIZATIONS'
export const SET_ORGANIZATIONS_CONTEXT = 'SET_ORGANIZATIONS_CONTEXT'

export const REMOVE_SORT = 'REMOVE_SORT'
export const CLEAR_SORTS = 'CLEAR_SORTS'
export const ADD_SORT = 'ADD_SORT'
export const EDIT_SORT = 'EDIT_SORT'
export const REMOVE_FILTER = 'REMOVE_FILTER'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const ADD_FILTER = 'ADD_FILTER'
export const EDIT_FILTER = 'EDIT_FILTER'
